/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIinterface */

#ifndef _Included_JNIinterface
#define _Included_JNIinterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIinterface
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIinterface_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNIinterface
 * Method:    test1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIinterface_test1
  (JNIEnv *, jobject);

/*
 * Class:     JNIinterface
 * Method:    initAll
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIinterface_initAll
  (JNIEnv *, jobject);

/*
 * Class:     JNIinterface
 * Method:    runStep
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIinterface_runStep
  (JNIEnv *, jobject);

/*
 * Class:     JNIinterface
 * Method:    cleanup
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIinterface_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     JNIinterface
 * Method:    isSimulationComplete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JNIinterface_isSimulationComplete
  (JNIEnv *, jobject);

/*
 * Class:     JNIinterface
 * Method:    getResultSnapshot
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_JNIinterface_getResultSnapshot
  (JNIEnv *, jobject);

/*
 * Class:     JNIinterface
 * Method:    simulateHelperCleanup
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JNIinterface_simulateHelperCleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
