/*
  Copyright (c) 2006-2007 Harri Kaimio
  
  This file is part of Photovault.

  Photovault is free software; you can redistribute it and/or modify it
  under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Photovault is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Photovault; if not, write to the Free Software Foundation,
  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
*/

package org.photovault.swingui.db;

import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import javax.swing.event.DocumentEvent;
import org.photovault.common.PhotovaultException;
import org.photovault.imginfo.Volume;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.photovault.common.PVDatabase;
import org.photovault.common.PhotovaultSettings;

/**
 * This dialog is used to enter setup for a new Photovault database and to 
 * create it.
 * @author  Harri Kaimio
 */
public class DbSettingsDlg extends javax.swing.JDialog {
    
    /** Creates new form DbSettingsDlg */
    public DbSettingsDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        dirChooser = new javax.swing.JFileChooser();
        instanceTypeBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        volumeDirFld = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        dirSelectBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nameFld = new javax.swing.JTextField();
        sqlDbPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dbHostFld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dbNameFld = new javax.swing.JTextField();
        derbyBtn = new javax.swing.JRadioButton();
        dbServerBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Photovault database");
        setName("Database settings");
        jLabel1.setText("Photo directory");

        okBtn.setText("OK");
        okBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                okBtnMouseClicked(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        dirSelectBtn.setText("...");
        dirSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirSelectBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Database name");

        nameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFldActionPerformed(evt);
            }
        });
        nameFld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFldFocusLost(evt);
            }
        });

        sqlDbPane.setBorder(javax.swing.BorderFactory.createTitledBorder("MySQL settings"));
        jLabel2.setText("MySQL host");

        dbHostFld.setEnabled(false);

        jLabel3.setText("Database name");

        dbNameFld.setEnabled(false);

        org.jdesktop.layout.GroupLayout sqlDbPaneLayout = new org.jdesktop.layout.GroupLayout(sqlDbPane);
        sqlDbPane.setLayout(sqlDbPaneLayout);
        sqlDbPaneLayout.setHorizontalGroup(
            sqlDbPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, sqlDbPaneLayout.createSequentialGroup()
                .addContainerGap()
                .add(sqlDbPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sqlDbPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(dbHostFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .add(dbNameFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap())
        );
        sqlDbPaneLayout.setVerticalGroup(
            sqlDbPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(sqlDbPaneLayout.createSequentialGroup()
                .add(sqlDbPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(dbHostFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE))
                .add(14, 14, 14)
                .add(sqlDbPaneLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(dbNameFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        sqlDbPane.getAccessibleContext().setAccessibleName("Database server");

        instanceTypeBtnGroup.add(derbyBtn);
        derbyBtn.setSelected(true);
        derbyBtn.setText("Internal database engine");
        derbyBtn.setActionCommand("useDerby");
        derbyBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        derbyBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        derbyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derbyBtnActionPerformed(evt);
            }
        });

        instanceTypeBtnGroup.add(dbServerBtn);
        dbServerBtn.setText("MySQL server");
        dbServerBtn.setActionCommand("useMySQL");
        dbServerBtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        dbServerBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        dbServerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbServerBtnActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(31, 31, 31)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel1))
                        .add(23, 23, 23)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(nameFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(volumeDirFld, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(dirSelectBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(derbyBtn)
                            .add(dbServerBtn)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(sqlDbPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(257, Short.MAX_VALUE)
                        .add(okBtn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 59, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(CancelBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(nameFld, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(volumeDirFld)
                    .add(dirSelectBtn)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(derbyBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(dbServerBtn)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(sqlDbPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(CancelBtn)
                    .add(okBtn))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameFldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFldFocusLost
        dbNameChanged();
    }//GEN-LAST:event_nameFldFocusLost

    /**
     When Photovault database name is changed set the volume directory to point 
     to ${user.home}/dbName if 
     <ul>
     <li>User has not entered a volume directory and</li>
     <li>The directory name that would be generated automatically does not exist
     (to avoid overwriting existing data</li>
     </ul>
     */
    private void nameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFldActionPerformed
        dbNameChanged();
    }//GEN-LAST:event_nameFldActionPerformed

    private void dbNameChanged() {
        String dbName = nameFld.getText();
        String volumeDirPath = volumeDirFld.getText();
        if ( volumeDirPath == null || volumeDirPath.length() == 0 ) {
            File homeDir = new File( System.getProperty( "user.home" ) );
            File pvDir = new File( homeDir, dbName );
            if ( !pvDir.exists() ) {
                volumeDirPath = pvDir.getAbsolutePath();
                volumeDirFld.setText( volumeDirPath );
            }
        }
        
    }
    
    /**
        Called when the user selects that he wants to create a MySql database
     */
    private void dbServerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbServerBtnActionPerformed
        dbHostFld.setEnabled( true );
        dbNameFld.setEnabled( true );
    }//GEN-LAST:event_dbServerBtnActionPerformed

    /**
        Called when user selects that he wants do create a Derby database
     */
    private void derbyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derbyBtnActionPerformed
        dbHostFld.setEnabled( false );
        dbNameFld.setEnabled( false );        
    }//GEN-LAST:event_derbyBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        retval = CANCEL_OPTION;
        setVisible( false );
    }//GEN-LAST:event_CancelBtnActionPerformed

    /**
     * Display a file selection dialog for selecting the volume folder
     */
    private void dirSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirSelectBtnActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode( fc.DIRECTORIES_ONLY );
        
        /* Set the starting directory for file chooser. If a directory name has been
         * entered into the box, use it as an starting point. Otherwise use 
         * user's home directory
         */
        String dirname = volumeDirFld.getText();
        if ( dirname.length() == 0 ) {
            dirname = System.getProperty( "user.home" );
        }
        File startingDir = new File( dirname );
        fc.setCurrentDirectory( startingDir );
        
        if ( fc.showDialog( this, "OK" ) == JFileChooser.APPROVE_OPTION ) {
            File volumeDir = fc.getSelectedFile();
            this.volumeDirFld.setText( volumeDir.getAbsolutePath() );
        }
    }//GEN-LAST:event_dirSelectBtnActionPerformed

    private void okBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_okBtnMouseClicked
        createDatabase();
        retval = APPROVE_OPTION;
        setVisible( false );
    }//GEN-LAST:event_okBtnMouseClicked
    
    /**
     * Error happened during dialog processing
     */
    public static final int ERROR_OPTION = 0;

    /**
     * User approved the dialog
     */
    public static final int APPROVE_OPTION = 1;
    
    /**
     * User canceled the dialog
     */
    public static final int CANCEL_OPTION = 2;
    
    /**
     * Return value for the dialog.
     */
    int retval;
    
    /**
     * Shows the dialog and waiths until user either approves or cancels it
     * @return Reason for dialog dismissal, either
     * <ul>
     * <li> APPROVE_OPTION - the dialog was approved
     * <li> CANCEL_OPTION - user canceled the dialog
     * <li> ERROR_OPTION - SOme kind of error happened during the dialog
     * </ul>
     *
     */
    public int showDialog( ) {
        // Center the dialog on screen
        int w = getSize().width;
        int h = getSize().height;
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (screenSize.width-w)/2;
        int y = (screenSize.height-h)/2;
        setLocation( x, y );
        
        retval = ERROR_OPTION;
        setVisible( true );
        return retval;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DbSettingsDlg dlg = new DbSettingsDlg(new javax.swing.JFrame(), true);
                dlg.showDialog();
            }
        });
    }
    
    private boolean createDatabase() {
        // Ask for the admin password
        try {
            PVDatabase db = new PVDatabase();
            db.setName( nameFld.getText() );
            db.setDataDirectory( new File( volumeDirFld.getText() ) );
            PhotovaultSettings settings = PhotovaultSettings.getSettings();
            settings.addDatabase( db );
            String user = "";
            String passwd = "";
            if ( dbServerBtn.isSelected() ) {
                AdminLoginDlg loginDlg = new AdminLoginDlg( this, true );
                if ( loginDlg.showDialog() == AdminLoginDlg.LOGIN_DLG_OK ) {
                    user = loginDlg.getUsername();
                    passwd = loginDlg.getPasswd();
                }
                db.setDbName( dbNameFld.getText() );
                db.setHost( dbHostFld.getText() );
//                Volume vol = new Volume( "defaultVolume", volumeDirFld.getText() );
//                try {
//                    db.addVolume( vol );
//                } catch (PhotovaultException ex) {
//                    // Should not happen...
//                }
            } else {
                // Creating an embedded database
                db.setInstanceType( PVDatabase.TYPE_EMBEDDED );
            }
            db.createDatabase( user, passwd );
            settings.saveDbConfig( db );
        } catch (PhotovaultException ex) {
            JOptionPane.showMessageDialog( this, ex.getMessage(),
                    "Error creating database", JOptionPane.ERROR_MESSAGE );
            return false;
        } catch ( IOException ex ) {
            JOptionPane.showMessageDialog( this, ex.getMessage(),
                    "Error saving database configuration",
                    JOptionPane.ERROR_MESSAGE );
            return false;

        }
        
        JOptionPane.showMessageDialog( this,
                "Database " + nameFld.getText() + " created successfully",
                "Database created", JOptionPane.INFORMATION_MESSAGE );
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField dbHostFld;
    private javax.swing.JTextField dbNameFld;
    private javax.swing.JRadioButton dbServerBtn;
    private javax.swing.JRadioButton derbyBtn;
    private javax.swing.JFileChooser dirChooser;
    private javax.swing.JButton dirSelectBtn;
    private javax.swing.ButtonGroup instanceTypeBtnGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameFld;
    private javax.swing.JButton okBtn;
    private javax.swing.JPanel sqlDbPane;
    private javax.swing.JTextField volumeDirFld;
    // End of variables declaration//GEN-END:variables
    
}
