Functional Mockup Interface For EnergyPlus: fmuTemplate.c File Reference
fmuTemplate.c File Reference
Functions
static fmiBoolean invalidNumber (ModelInstance *comp, const char *f, const char *arg, int n, int nExpected)
static fmiBoolean invalidState (ModelInstance *comp, const char *f, int statesExpected)
static fmiBoolean nullPointer (ModelInstance *comp, const char *f, const char *arg, const void *p)
static fmiBoolean vrOutOfRange (ModelInstance *comp, const char *f, fmiValueReference vr, int end)
const char * fmiGetTypesPlatform ()
const char * fmiGetVersion ()
fmiComponent fmiInstantiateSlave (fmiString instanceName, fmiString GUID, fmiString fmuLocation, fmiString mimeType, fmiReal timeout, fmiBoolean visible, fmiBoolean interactive, fmiCallbackFunctions functions, fmiBoolean loggingOn)
fmiStatus fmiSetDebugLogging (fmiComponent c, fmiBoolean loggingOn)
void fmiFreeSlaveInstance (fmiComponent c)
fmiStatus fmiSetReal (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiReal value[])
fmiStatus fmiSetInteger (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiInteger value[])
fmiStatus fmiSetBoolean (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiBoolean value[])
fmiStatus fmiSetString (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiString value[])
fmiStatus fmiGetReal (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiReal value[])
fmiStatus fmiGetInteger (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiInteger value[])
fmiStatus fmiGetBoolean (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiBoolean value[])
fmiStatus fmiGetString (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiString value[])
fmiStatus fmiGetNominalContinuousStates (fmiComponent c, fmiReal x_nominal[], size_t nx)
fmiStatus fmiInitializeSlave (fmiComponent c, fmiReal tStart, fmiBoolean StopTimeDefined, fmiReal tStop)
Function Documentation
void fmiFreeSlaveInstance (fmiComponent c)
Definition at line 152 of file fmuTemplate.c.
References ModelInstance::b, fmiOK, fmiCallbackFunctions::freeMemory, ModelInstance::functions, i, ModelInstance::i, ModelInstance::instanceName, fmiCallbackFunctions::logger, ModelInstance::loggingOn, ModelInstance::r, and ModelInstance::s.
fmiStatus fmiGetBoolean (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiBoolean value[])
Definition at line 354 of file fmuTemplate.c.
References ModelInstance::b, fmiError, fmiOK, ModelInstance::functions, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, not_modelError, nullPointer(), and vrOutOfRange().
fmiStatus fmiGetInteger (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiInteger value[])
Definition at line 335 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, ModelInstance::i, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, not_modelError, nullPointer(), and vrOutOfRange().
fmiStatus fmiGetNominalContinuousStates (fmiComponent c, fmiReal x_nominal[], size_t nx)
Definition at line 433 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, i, ModelInstance::instanceName, invalidNumber(), invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, not_modelError, and nullPointer().
fmiStatus fmiGetReal (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiReal value[])
Definition at line 314 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, not_modelError, nullPointer(), and vrOutOfRange().
fmiStatus fmiGetString (fmiComponent c, const fmiValueReference vr[], size_t nvr, fmiString value[])
Definition at line 373 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, not_modelError, nullPointer(), ModelInstance::s, and vrOutOfRange().
const char* fmiGetTypesPlatform ()
Definition at line 72 of file fmuTemplate.c.
References fmiTypesPlatform.
const char* fmiGetVersion ()
Definition at line 76 of file fmuTemplate.c.
References fmiVersion.
fmiStatus fmiInitializeSlave (fmiComponent c, fmiReal tStart, fmiBoolean StopTimeDefined, fmiReal tStop)
Definition at line 496 of file fmuTemplate.c.
References fmiError, fmiOK, invalidState(), modelInitialized, modelInstantiated, and ModelInstance::state.
fmiComponent fmiInstantiateSlave (fmiString instanceName, fmiString GUID, fmiString fmuLocation, fmiString mimeType, fmiReal timeout, fmiBoolean visible, fmiBoolean interactive, fmiCallbackFunctions functions, fmiBoolean loggingOn)
Definition at line 87 of file fmuTemplate.c.
References fmiCallbackFunctions::allocateMemory, ModelInstance::b, fmiError, fmiOK, fmiCallbackFunctions::freeMemory, ModelInstance::functions, ModelInstance::GUID, ModelInstance::i, ModelInstance::instanceName, ModelInstance::isPositive, fmiCallbackFunctions::logger, ModelInstance::loggingOn, modelInstantiated, ModelInstance::r, ModelInstance::s, and ModelInstance::state.
fmiStatus fmiSetBoolean (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiBoolean value[])
Definition at line 218 of file fmuTemplate.c.
References ModelInstance::b, fmiError, fmiOK, ModelInstance::functions, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, modelInitialized, modelInstantiated, nullPointer(), and vrOutOfRange().
fmiStatus fmiSetDebugLogging (fmiComponent c, fmiBoolean loggingOn)
Definition at line 141 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, and not_modelError.
fmiStatus fmiSetInteger (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiInteger value[])
Definition at line 197 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, ModelInstance::i, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, modelInitialized, modelInstantiated, nullPointer(), and vrOutOfRange().
fmiStatus fmiSetReal (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiReal value[])
Definition at line 175 of file fmuTemplate.c.
References fmiError, fmiOK, ModelInstance::functions, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, modelInitialized, modelInstantiated, nullPointer(), ModelInstance::r, and vrOutOfRange().
fmiStatus fmiSetString (fmiComponent c, const fmiValueReference vr[], size_t nvr, const fmiString value[])
Definition at line 239 of file fmuTemplate.c.
References fmiCallbackFunctions::allocateMemory, fmiError, fmiOK, fmiCallbackFunctions::freeMemory, ModelInstance::functions, i, ModelInstance::instanceName, invalidState(), fmiCallbackFunctions::logger, ModelInstance::loggingOn, modelError, modelInitialized, modelInstantiated, nullPointer(), ModelInstance::s, ModelInstance::state, and vrOutOfRange().
static fmiBoolean invalidNumber (ModelInstance * comp, const char * f, const char * arg, int n, int nExpected) [static]
Definition at line 22 of file fmuTemplate.c.
References fmiError, fmiFalse, fmiTrue, ModelInstance::functions, ModelInstance::instanceName, fmiCallbackFunctions::logger, modelError, and ModelInstance::state.
Referenced by fmiGetNominalContinuousStates().
static fmiBoolean invalidState (ModelInstance * comp, const char * f, int statesExpected) [static]
Definition at line 32 of file fmuTemplate.c.
References fmiError, fmiFalse, fmiTrue, ModelInstance::functions, ModelInstance::instanceName, fmiCallbackFunctions::logger, modelError, and ModelInstance::state.
Referenced by fmiGetBoolean(), fmiGetInteger(), fmiGetNominalContinuousStates(), fmiGetReal(), fmiGetString(), fmiInitializeSlave(), fmiSetBoolean(), fmiSetDebugLogging(), fmiSetInteger(), fmiSetReal(), and fmiSetString().
static fmiBoolean nullPointer (ModelInstance * comp, const char * f, const char * arg, const void * p) [static]
Definition at line 44 of file fmuTemplate.c.
References fmiError, fmiFalse, fmiTrue, ModelInstance::functions, ModelInstance::instanceName, fmiCallbackFunctions::logger, modelError, and ModelInstance::state.
Referenced by fmiGetBoolean(), fmiGetInteger(), fmiGetNominalContinuousStates(), fmiGetReal(), fmiGetString(), fmiSetBoolean(), fmiSetInteger(), fmiSetReal(), and fmiSetString().
static fmiBoolean vrOutOfRange (ModelInstance * comp, const char * f, fmiValueReference vr, int end) [static]
Definition at line 54 of file fmuTemplate.c.
References fmiError, fmiFalse, fmiTrue, ModelInstance::functions, ModelInstance::instanceName, fmiCallbackFunctions::logger, and ModelInstance::state.
Referenced by fmiGetBoolean(), fmiGetInteger(), fmiGetReal(), fmiGetString(), fmiSetBoolean(), fmiSetInteger(), fmiSetReal(), and fmiSetString().