Functional Mockup Interface For EnergyPlus: main.c File Reference
parser/main.c File Reference
#include "main.h"
#include "string.h"
#include "../common/util.h"
#include <sys/stat.h>
Defines
#define XML_FILE "modelDescription.xml"
Functions
int callparser (const char *fmuFilNam, const char *tmpPat)
Call the parser and save the information in fmu.modelDescription.
int delete (char *tmpPat)
Delete the temporary folder.
void help ()
Print help information.
int main (int argc, const char *argv[])
Main routine of parser.
Variables
FMU fmu
Define Documentation
#define XML_FILE "modelDescription.xml"
Definition at line 25 of file parser/main.c.
Referenced by callparser().
Function Documentation
int callparser (const char * fmuFilNam, const char * tmpPat)
Call the parser and save the information in fmu.modelDescription.
Parameters:
fmuFilNam The name of fmu file
tmpPat Temporary path of the fmu file
Returns:
0 if no error occurred
Definition at line 36 of file parser/main.c.
References getModelIdentifier(), FMU::modelDescription, parse(), PATH_SEP, printfDebug(), printfError(), and XML_FILE.
Referenced by main().
int delete (char * tmpPat)
Delete the temporary folder.
Parameters:
tmpPat The path of the tmeporary folder
Returns:
0 if no error occurred
Definition at line 63 of file parser/main.c.
References printDebug(), printError(), printfDebug(), printfError(), and WINDOWS.
void help ()
Print help information.
Definition at line 100 of file parser/main.c.
Referenced by main().
int main (int argc, const char * argv[])
Main routine of parser.
Parameters:
argc Number of arguments
argv Arguments
Returns:
0 if no error occurred
Definition at line 134 of file parser/main.c.
References callparser(), help(), i, opt_delete, opt_help, opt_printidf, opt_unpack, printDebug(), printError(), printfDebug(), printfError(), setDebug(), and unpack().
Variable Documentation
FMU fmu
Definition at line 27 of file parser/main.c.