Functional Mockup Interface For EnergyPlus: parser.c File Reference
parser.c File Reference
Methods for master program that interacts with an FMU for co-simulation.
#include "parser.h"
#include "string.h"
#include "../common/util.h"
Defines
#define XML_FILE "modelDescription.xml"
Functions
int callparser (const char *fmuFilNam, const char *tmpPat)
Call the parser and save the information in fmu.modelDescription.
void help ()
Print help information.
int main (int argc, char *argv[])
Main routine of parser.
Variables
FMU fmu
Detailed Description
Methods for master program that interacts with an FMU for co-simulation.
Author:
Wangda Zuo, Thierry S. Nouidui, Michael Wetter Simulation Research Group, LBNL, WZuo@lbl.gov
Date:
2011-11-02
This file parse the FMU for co-simulation and translate related information into Energyplus input file (.idf)
Definition in file parser.c.
Define Documentation
#define XML_FILE "modelDescription.xml"
Definition at line 25 of file parser.c.
Referenced by callparser().
Function Documentation
int callparser (const char * fmuFilNam, const char * tmpPat)
Call the parser and save the information in fmu.modelDescription.
Parameters:
fmuFilNam The name of fmu file
tmpPat Temporary path of the fmu file
Returns:
0 if no error occurred
Definition at line 36 of file parser.c.
References getModelIdentifier(), FMU::modelDescription, parse(), PATH_SEP, printfDebug(), printfError(), and XML_FILE.
Referenced by main().
void help ()
Print help information.
Definition at line 62 of file parser.c.
Referenced by main().
int main (int argc, char * argv[])
Main routine of parser.
Parameters:
argc Number of arguments
argv Arguments
Returns:
0 if no error occurred
Definition at line 101 of file parser.c.
References callparser(), getTmpPath(), help(), i, opt_delete, opt_help, opt_printidf, opt_unpack, printDebug(), printError(), printfDebug(), printfError(), setDebug(), unpack(), and WINDOWS.
Variable Documentation
FMU fmu
Definition at line 27 of file parser.c.