Functional Mockup Interface For EnergyPlus: stack.c File Reference
stack.c File Reference
#include <stdio.h>
#include <assert.h>
#include <malloc.h>
#include "stack.h"
Functions
Stack * stackNew (int initialSize, int inc)
int stackIsEmpty (Stack *s)
int stackPush (Stack *s, void *e)
void * stackPeek (Stack *s)
void * stackPop (Stack *s)
void ** stackLastPopedAsArray0 (Stack *s, int n)
void ** stackPopAllAsArray (Stack *s, int *size)
void stackFree (Stack *s)
Function Documentation
void stackFree (Stack * s)
Definition at line 80 of file stack.c.
References Stack::stack.
Referenced by cleanup().
int stackIsEmpty (Stack * s)
Definition at line 22 of file stack.c.
References Stack::stackPos.
Referenced by checkPeek(), parse(), stackPeek(), and stackPop().
void** stackLastPopedAsArray0 (Stack * s, int n)
Definition at line 55 of file stack.c.
References i, Stack::stack, and Stack::stackPos.
Referenced by popList().
Stack* stackNew (int initialSize, int inc)
Definition at line 12 of file stack.c.
References Stack::inc, Stack::initialSize, Stack::stack, Stack::stackPos, and Stack::stackSize.
Referenced by parse().
void* stackPeek (Stack * s)
Definition at line 41 of file stack.c.
References Stack::stack, stackIsEmpty(), and Stack::stackPos.
Referenced by checkPeek(), and endElement().
void* stackPop (Stack * s)
Definition at line 48 of file stack.c.
References Stack::stack, stackIsEmpty(), and Stack::stackPos.
Referenced by checkPop(), parse(), and popList().
void** stackPopAllAsArray (Stack * s, int * size)
Definition at line 68 of file stack.c.
References i, Stack::stack, and Stack::stackPos.
int stackPush (Stack * s, void * e)
Definition at line 28 of file stack.c.
References Stack::inc, Stack::initialSize, Stack::stack, Stack::stackPos, and Stack::stackSize.
Referenced by endElement(), popList(), and startElement().