Functional Mockup Interface For EnergyPlus: xml_parser_cosim.h File Reference
xml_parser_cosim.h File Reference
#include "expat.h"
#include "fmiModelTypes.h"
#include "stack.h"
Classes
struct Element
struct ListElement
struct Type
struct ScalarVariable
struct ModelDescription
Defines
#define XML_STATIC
This file is based on xml_parser.c that is copyrighted by QTronic GmbH and that is distributed under the BSD license.
#define SIZEOF_ELM 31
#define SIZEOF_ATT 47
#define SIZEOF_ENU 13
Enumerations
enum Elm {
elm_fmiModelDescription, elm_UnitDefinitions, elm_BaseUnit, elm_DisplayUnitDefinition,
elm_TypeDefinitions, elm_Type, elm_RealType, elm_IntegerType,
elm_BooleanType, elm_StringType, elm_EnumerationType, elm_Item,
elm_DefaultExperiment, elm_VendorAnnotations, elm_Tool, elm_Annotation,
elm_ModelVariables, elm_ScalarVariable, elm_DirectDependency, elm_Name,
elm_Real, elm_Integer, elm_Boolean, elm_String,
elm_Enumeration, elm_Implementation, elm_CoSimulation_StandAlone, elm_Capabilities,
elm_CoSimulation_Tool, elm_CoSimulationModel, elm_File
}
enum Att {
att_fmiVersion, att_displayUnit, att_gain, att_offset,
att_unit, att_name, att_description, att_quantity,
att_relativeQuantity, att_min, att_max, att_nominal,
att_declaredType, att_start, att_fixed, att_startTime,
att_stopTime, att_tolerance, att_value, att_valueReference,
att_variability, att_causality, att_alias, att_modelName,
att_modelIdentifier, att_guid, att_author, att_version,
att_generationTool, att_generationDateAndTime, att_variableNamingConvention, att_numberOfContinuousStates,
att_numberOfEventIndicators, att_input, att_canHandleVariableCommunicationStepSize, att_canHandleEvents,
att_canRejectSteps, att_canInterpolateInputs, att_maxOutputDerivativeOrder, att_canRunAsynchronuously,
att_canSignalEvents, att_canBeInstantiatedOnlyOncePerProcess, att_canNotUseMemoryManagementFunctions, att_entryPoint,
att_manualStart, att_type, att_file
}
enum Enu {
enu_flat, enu_structured, enu_constant, enu_parameter,
enu_discrete, enu_continuous, enu_input, enu_output,
enu_internal, enu_none, enu_noAlias, enu_alias,
enu_negatedAlias
}
enum AstNodeType {
astElement, astListElement, astType, astScalarVariable,
astImplementation, astModelDescription
}
enum ValueStatus { valueMissing, valueDefined, valueIllegal }
Functions
ModelDescription * parse (const char *xmlPath)
Parse the fmu.
const char * getString (void *element, Att a)
Get string.
const char * getMyString (ModelDescription *element, Att a)
Get string.
double getDouble (void *element, Att a, ValueStatus *vs)
Get real value.
int getInt (void *element, Att a, ValueStatus *vs)
Retrieve Enumeration values from XML, e.g.
unsigned int getUInt (void *element, Att a, ValueStatus *vs)
Get unsigned integer.
char getBoolean (void *element, Att a, ValueStatus *vs)
Get the boolean value.
Enu getEnumValue (void *element, Att a, ValueStatus *vs)
Retrieve the value of the given built-in enum attribute.
void freeElement (void *element)
Free element which may contain list of elements.
const char * getModelIdentifier (ModelDescription *md)
Get model identifier.
int getNumberOfStates (ModelDescription *md)
Get number of states.
int getNumberOfEventIndicators (ModelDescription *md)
Get number of event indicators.
const char * getName (void *element)
Get name.
Enu getCausality (void *scalarVariable)
Get causality.
Enu getVariability (void *scalarVariable)
Get variablity.
Enu getAlias (void *scalarVariable)
Get alias.
fmiValueReference getValueReference (void *scalarVariable)
Get value reference.
ScalarVariable * getVariableByName (ModelDescription *md, const char *name)
Get the varible by its unique name.
ScalarVariable * getVariable (ModelDescription *md, fmiValueReference vr, Elm type)
Get scalar variable.
Type * getDeclaredType (ModelDescription *md, const char *declaredType)
Get declared type of element.
const char * getString2 (ModelDescription *md, void *sv, Att a)
const char * getDescription (ModelDescription *md, ScalarVariable *sv)
Get description from variable or from declared type, or NULL.
const char * getVariableAttributeString (ModelDescription *md, fmiValueReference vr, Elm type, Att a)
Check the attribute defined by vr and type.
double getVariableAttributeDouble (ModelDescription *md, fmiValueReference vr, Elm type, Att a, ValueStatus *vs)
Get attribute value from scalar variable given by vr and type, incude default value provided by declared type, if any.
double getNominal (ModelDescription *md, fmiValueReference vr)
Get nominal value from real variable or its declared type.
Variables
const char * elmNames [SIZEOF_ELM]
const char * attNames [SIZEOF_ATT]
const char * enuNames [SIZEOF_ENU]
Define Documentation
#define SIZEOF_ATT 47
Definition at line 31 of file xml_parser_cosim.h.
Referenced by checkAttribute().
#define SIZEOF_ELM 31
Definition at line 28 of file xml_parser_cosim.h.
Referenced by checkElement().
#define SIZEOF_ENU 13
Definition at line 34 of file xml_parser_cosim.h.
Referenced by checkEnumValue().
#define XML_STATIC
This file is based on xml_parser.c that is copyrighted by QTronic GmbH and that is distributed under the BSD license.
The original file, its copyright notice and its license can be found in ../3rdParty
The file has been modified and renamed to xml_parser_cosim.c for use with the FMU standard for co-simulation. The original file was developed for model exchange. Copyright notice of original file that served as the basis of this imlementation.
Definition at line 22 of file xml_parser_cosim.h.
Enumeration Type Documentation
enum AstNodeType
Enumerator:
astElement
astListElement
astType
astScalarVariable
astImplementation
astModelDescription
Definition at line 120 of file xml_parser_cosim.h.
enum Att
Enumerator:
att_fmiVersion
att_displayUnit
att_gain
att_offset
att_unit
att_name
att_description
att_quantity
att_relativeQuantity
att_min
att_max
att_nominal
att_declaredType
att_start
att_fixed
att_startTime
att_stopTime
att_tolerance
att_value
att_valueReference
att_variability
att_causality
att_alias
att_modelName
att_modelIdentifier
att_guid
att_author
att_version
att_generationTool
att_generationDateAndTime
att_variableNamingConvention
att_numberOfContinuousStates
att_numberOfEventIndicators
att_input
att_canHandleVariableCommunicationStepSize
att_canHandleEvents
att_canRejectSteps
att_canInterpolateInputs
att_maxOutputDerivativeOrder
att_canRunAsynchronuously
att_canSignalEvents
att_canBeInstantiatedOnlyOncePerProcess
att_canNotUseMemoryManagementFunctions
att_entryPoint
att_manualStart
att_type
att_file
Definition at line 52 of file xml_parser_cosim.h.
enum Elm
Enumerator:
elm_fmiModelDescription
elm_UnitDefinitions
elm_BaseUnit
elm_DisplayUnitDefinition
elm_TypeDefinitions
elm_Type
elm_RealType
elm_IntegerType
elm_BooleanType
elm_StringType
elm_EnumerationType
elm_Item
elm_DefaultExperiment
elm_VendorAnnotations
elm_Tool
elm_Annotation
elm_ModelVariables
elm_ScalarVariable
elm_DirectDependency
elm_Name
elm_Real
elm_Integer
elm_Boolean
elm_String
elm_Enumeration
elm_Implementation
elm_CoSimulation_StandAlone
elm_Capabilities
elm_CoSimulation_Tool
elm_CoSimulationModel
elm_File
Definition at line 40 of file xml_parser_cosim.h.
enum Enu
Enumerator:
enu_flat
enu_structured
enu_constant
enu_parameter
enu_discrete
enu_continuous
enu_input
enu_output
enu_internal
enu_none
enu_noAlias
enu_alias
enu_negatedAlias
Definition at line 65 of file xml_parser_cosim.h.
enum ValueStatus
Enumerator:
valueMissing
valueDefined
valueIllegal
Definition at line 130 of file xml_parser_cosim.h.
Function Documentation
void freeElement (void * element)
Free element which may contain list of elements.
Parameters:
element point of element.
Definition at line 1101 of file xml_parser_cosim.c.
References astListElement, astModelDescription, astScalarVariable, astType, Element::attributes, ModelDescription::defaultExperiment, freeElement(), freeList(), getAstNodeType(), i, ModelDescription::implementation, ModelDescription::modelVariables, Element::n, Element::type, ModelDescription::typeDefinitions, ModelDescription::unitDefinitions, and ModelDescription::vendorAnnotations.
Referenced by freeElement(), freeList(), main(), and parse().
Enu getAlias (void * scalarVariable)
Get alias.
Parameters:
scalarVariable Scalar variable.
Returns:
Value of noAlias, alias, negatedAlias. If value is missing, the default noAlias is returned.
Definition at line 306 of file xml_parser_cosim.c.
References att_alias, and getEnumValue().
Referenced by outputRow(), and simulate().
char getBoolean (void * element, Att a, ValueStatus * vs)
Get the boolean value.
Parameters:
element element.
a Attribute.
vs Value status.
Returns:
1 for true and 0 for false.
Definition at line 182 of file xml_parser_cosim.c.
References getString(), valueDefined, valueIllegal, and valueMissing.
Enu getCausality (void * scalarVariable)
Get causality.
Parameters:
scalarVariable Scalar variable.
Returns:
One of: input, output, internal, none. If value is missing, the default internal is returned.
Definition at line 282 of file xml_parser_cosim.c.
References att_causality, and getEnumValue().
Referenced by simulate().
Type* getDeclaredType (ModelDescription * md, const char * declaredType)
Get declared type of element.
Parameters:
md Model description.
declaredType Declared type.
Returns:
Point of type definition if there is no error occurred. Otherwise, NULL.
Definition at line 387 of file xml_parser_cosim.c.
References getName(), i, and ModelDescription::typeDefinitions.
Referenced by getDescription(), and getVariableAttributeString().
const char* getDescription (ModelDescription * md, ScalarVariable * sv)
Get description from variable or from declared type, or NULL.
Parameters:
md Model description.
md sv Scalar variable.
Returns:
Attribute description or type or NULL.
Definition at line 414 of file xml_parser_cosim.c.
References att_declaredType, att_description, getDeclaredType(), getString(), and ScalarVariable::typeSpec.
double getDouble (void * element, Att a, ValueStatus * vs)
Get real value.
Parameters:
element element
a Attribute
vs Value status.
Returns:
Value of a if there is no error occurred. Otherwise, 0.
Definition at line 133 of file xml_parser_cosim.c.
References getString(), valueDefined, valueIllegal, and valueMissing.
Enu getEnumValue (void * element, Att a, ValueStatus * vs)
Retrieve the value of the given built-in enum attribute.
If the value is missing, this is marked in the ValueStatus and the corresponding default is returned.
Parameters:
element Element.
Returns:
-1 or a globally unique id for the value such that enuNames[id] is the string representation of the enum value.
Definition at line 203 of file xml_parser_cosim.c.
References att_alias, att_causality, att_variability, att_variableNamingConvention, checkEnumValue(), enu_continuous, enu_flat, enu_internal, enu_noAlias, getString(), valueDefined, valueIllegal, and valueMissing.
Referenced by getAlias(), getCausality(), and getVariability().
int getInt (void * element, Att a, ValueStatus * vs)
Retrieve Enumeration values from XML, e.g.
the start value for a variable of user-defined enumeration type.
Parameters:
element element
a Attribute
vs Value status.
Returns:
Value of a if there is no error occurred. Otherwise, 0.
Definition at line 150 of file xml_parser_cosim.c.
References getString(), valueDefined, valueIllegal, and valueMissing.
Referenced by getNumberOfEventIndicators().
const char* getModelIdentifier (ModelDescription * md)
Get model identifier.
Convenience methods for accessing the model description. Use is only safe after the ast has been successfuly validated.
Parameters:
md Model description.
Returns:
Model ID.
Definition at line 229 of file xml_parser_cosim.c.
References att_modelIdentifier, and getMyString().
Referenced by callparser(), getAdr(), main(), and simulate().
const char* getMyString (ModelDescription * element, Att a)
Get string.
Parameters:
element Model description.
a Attribute
Returns:
The attribute of a.
Definition at line 115 of file xml_parser_cosim.c.
References attNames, Element::attributes, i, and Element::n.
Referenced by getModelIdentifier().
const char* getName (void * element)
Get name.
Name is a required attribute of ScalarVariable, Type, Item, Annotation, and Tool
Parameters:
element Element.
Returns:
Name.
Definition at line 269 of file xml_parser_cosim.c.
References att_name, and getString().
Referenced by getDeclaredType(), getVariableByName(), outputRow(), and replaceRefsInMessage().
double getNominal (ModelDescription * md, fmiValueReference vr)
Get nominal value from real variable or its declared type.
Parameters:
md Model description.
vr FMI value reference.
Returns:
Defined nonimal value. Otherwise, return 1.0 if no nominal value is defined.
Definition at line 475 of file xml_parser_cosim.c.
References att_nominal, elm_Real, getVariableAttributeDouble(), and valueDefined.
int getNumberOfEventIndicators (ModelDescription * md)
Get number of event indicators.
Parameters:
md Model description.
Returns:
Number of event indicators.
Definition at line 255 of file xml_parser_cosim.c.
References att_numberOfEventIndicators, getInt(), and valueDefined.
int getNumberOfStates (ModelDescription * md)
Get number of states.
Parameters:
md Model description.
Returns:
Number of states.
Definition at line 242 of file xml_parser_cosim.c.
References att_numberOfContinuousStates, getUInt(), and valueDefined.
const char* getString (void * element, Att a)
Get string.
Parameters:
element Element of xml data
a Attribute
Returns:
The attribute of a.
Definition at line 98 of file xml_parser_cosim.c.
References attNames, Element::attributes, i, and Element::n.
Referenced by getBoolean(), getDescription(), getDouble(), getEnumValue(), getInt(), getName(), getUInt(), getVariableAttributeString(), and simulate().
const char* getString2 (ModelDescription * md, void * sv, Att a)
unsigned int getUInt (void * element, Att a, ValueStatus * vs)
Get unsigned integer.
Parameters:
element element
a Attribute
vs Value status.
Returns:
Value of a if there is no error occurred. Otherwise, -1.
Definition at line 166 of file xml_parser_cosim.c.
References getString(), valueDefined, valueIllegal, and valueMissing.
Referenced by getNumberOfStates(), and getValueReference().
fmiValueReference getValueReference (void * scalarVariable)
Get value reference.
The vr is unique only for one of the 4 base data types r,i,b,s and may also be fmiUndefinedValueReference = 4294967295 = 0xFFFFFFFF here, i means integer or enumeration
Parameters:
scalarVariable Scalar variable.
Returns:
FMI value reference.
Definition at line 320 of file xml_parser_cosim.c.
References att_valueReference, elm_ScalarVariable, getUInt(), and valueDefined.
Referenced by getSV(), getVariable(), outputRow(), and simulate().
Enu getVariability (void * scalarVariable)
Get variablity.
Parameters:
scalarVariable Scalar variable.
Returns:
One of constant, parameter, discrete, continuous. If value is missing, the default continuous is returned.
Definition at line 294 of file xml_parser_cosim.c.
References att_variability, and getEnumValue().
ScalarVariable* getVariable (ModelDescription * md, fmiValueReference vr, Elm type)
Get scalar variable.
Parameters:
md Model description.
vr FMI value reference.
type Element.
Returns:
NULL if variable not found or vr==fmiUndefinedValueReference
Definition at line 368 of file xml_parser_cosim.c.
References fmiUndefinedValueReference, getValueReference(), i, ModelDescription::modelVariables, sameBaseType(), Element::type, and ScalarVariable::typeSpec.
Referenced by getVariableAttributeString().
double getVariableAttributeDouble (ModelDescription * md, fmiValueReference vr, Elm type, Att a, ValueStatus * vs)
Get attribute value from scalar variable given by vr and type, incude default value provided by declared type, if any.
Parameters:
md Model description.
vr FMI value reference.
type Element type.
a Attribute.
vs Value status.
Returns:
Attribute value if there is no error occurred. Otherwise, return 0.0.
Definition at line 459 of file xml_parser_cosim.c.
References getVariableAttributeString(), valueDefined, valueIllegal, and valueMissing.
Referenced by getNominal().
const char* getVariableAttributeString (ModelDescription * md, fmiValueReference vr, Elm type, Att a)
Check the attribute defined by vr and type.
Parameters:
md Model description.
vr FMI value reference.
type Element type.
a Attribute.
Returns:
String of attribute's value if there is no error occurred. Otherwise, return NULL.
Definition at line 433 of file xml_parser_cosim.c.
References att_declaredType, getDeclaredType(), getString(), getVariable(), Type::typeSpec, and ScalarVariable::typeSpec.
Referenced by getVariableAttributeDouble().
ScalarVariable* getVariableByName (ModelDescription * md, const char * name)
Get the varible by its unique name.
Parameters:
md Model description.
name Variable name.
Returns:
Point to scalar variable.
Definition at line 335 of file xml_parser_cosim.c.
References getName(), i, and ModelDescription::modelVariables.
Referenced by simulate().
ModelDescription* parse (const char * xmlPath)
Parse the fmu.
The receiver must call freeElement(md) to release AST memory.
Parameters:
xmlPath The xml file to be parsed
Returns:
the root node md of the AST if no error occurred. NULL to indicate failure
Definition at line 1166 of file xml_parser_cosim.c.
References checkPointer(), cleanup(), endElement(), freeElement(), handleData(), parser, printfError(), printidf(), stackIsEmpty(), stackNew(), stackPop(), startElement(), text, XML_ErrorString(), XML_GetErrorCode(), XML_Parse(), XML_ParserCreate(), XML_ParserFree(), XML_SetCharacterDataHandler(), XML_SetElementHandler(), and XMLBUFSIZE.
Referenced by callparser(), and main().
Variable Documentation
const char* attNames[SIZEOF_ATT]
Definition at line 65 of file xml_parser_cosim.c.
Referenced by addAttributes(), checkAttribute(), endElement(), getMyString(), and getString().
const char* elmNames[SIZEOF_ELM]
Definition at line 55 of file xml_parser_cosim.c.
Referenced by checkElement(), checkElementType(), checkPeek(), endElement(), logFatalTypeError(), printElement(), and startElement().
const char* enuNames[SIZEOF_ENU]
Definition at line 77 of file xml_parser_cosim.c.
Referenced by checkEnumValue().